# Generated by Django 5.0 on 2023-12-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
